# model 
model_id: YourModel

# multi-GPUs
use_mGPU: True

# validation
use_validation: True

# wandb
use_wandb: True
wandb_alert_thres: 1000

# root
train_dataset_root_list: [
                "/media/deep3090/새 볼륨/celeba_hq",
                # '/home/compu/dataset/CelebHQ',
                # '/home/compu/dataset/ffhq16k'
            ]
valid_dataset_root: assets/valid
save_root: train_result

# learning rate
lr_G: 0.0001
lr_D: 0.00001
beta1: 0
beta2: 0.999

# weight of loss
W_adv: 1
W_id: 5
W_recon: 10
W_cycle: 0
W_lpips: 0
W_attr: 10

# hyperparameters
same_prob: 0.2
batch_per_gpu: 4
max_step: 400000

# log cycle
loss_cycle: 10
test_cycle: 1000
ckpt_cycle: 10000

# ckpt path
# blank is None, but None is "None"
load_ckpt: False
ckpt_id: test
ckpt_step: 0
# ckpt_id: run0424
# ckpt_step: 30000

## Pretrained models paths
arcface_path: ptnn/arcface.pth
